import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import LandingNavbar from "@/components/navbar.component";
import AuthProvider from "@/contexts/auth.context";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id" className={`${inter.variable} ${playfair.variable}`}>
      <LandingNavbar />
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
